import {
  SiReact,
  SiNextdotjs,
  SiTypescript,
  SiTailwindcss,
  SiNodedotjs,
  SiExpress,
  SiPostgresql,
  SiSupabase,
  SiPrisma,
  SiExpo,
  SiThreedotjs,
  SiSqlite,
  SiMongodb,
  SiAnthropic,
  SiGooglegemini,
  SiVercel,
  SiCloudflare,
  SiClerk,
  SiContentful,
  SiUnity,
  SiBlender,
} from "react-icons/si";
import { FaAws, FaMicrosoft } from "react-icons/fa6";
import {
  LuBraces,
  LuDatabase,
  LuBot,
  LuNetwork,
  LuBoxes,
  LuTerminal,
  LuWorkflow,
  LuSparkles,
} from "react-icons/lu";
import type { IconType } from "react-icons";

/** Brand color per skill. Generics (non-brand) use the site's muted tone. */
export const SKILL_ICONS: Record<string, { icon: IconType; color: string }> = {
  React: { icon: SiReact, color: "#61DAFB" },
  "Next.js": { icon: SiNextdotjs, color: "#000000" },
  TypeScript: { icon: SiTypescript, color: "#3178C6" },
  "Tailwind CSS": { icon: SiTailwindcss, color: "#06B6D4" },
  "Node.js": { icon: SiNodedotjs, color: "#5FA04E" },
  "Express.js": { icon: SiExpress, color: "#000000" },
  PostgreSQL: { icon: SiPostgresql, color: "#4169E1" },
  Supabase: { icon: SiSupabase, color: "#3FCF8E" },
  Prisma: { icon: SiPrisma, color: "#2D3748" },
  "React Native": { icon: SiReact, color: "#61DAFB" },
  Expo: { icon: SiExpo, color: "#000020" },
  "Three.js": { icon: SiThreedotjs, color: "#000000" },
  "REST APIs": { icon: LuBraces, color: "#6b665c" },
  pgvector: { icon: LuDatabase, color: "#6b665c" },
  SQLite: { icon: SiSqlite, color: "#003B57" },
  MongoDB: { icon: SiMongodb, color: "#47A248" },
  OpenAI: { icon: LuSparkles, color: "#10A37F" },
  "Anthropic Claude": { icon: SiAnthropic, color: "#D97757" },
  Gemini: { icon: SiGooglegemini, color: "#4285F4" },
  "AI Agents": { icon: LuBot, color: "#6b665c" },
  RAG: { icon: LuNetwork, color: "#6b665c" },
  "Vector Embeddings": { icon: LuBoxes, color: "#6b665c" },
  "Prompt Engineering": { icon: LuTerminal, color: "#6b665c" },
  Flowise: { icon: LuWorkflow, color: "#6b665c" },
  Vercel: { icon: SiVercel, color: "#000000" },
  "AWS EC2": { icon: FaAws, color: "#FF9900" },
  Azure: { icon: FaMicrosoft, color: "#0078D4" },
  Cloudflare: { icon: SiCloudflare, color: "#F38020" },
  Clerk: { icon: SiClerk, color: "#6C47FF" },
  Contentful: { icon: SiContentful, color: "#2478CC" },
  Unity: { icon: SiUnity, color: "#222222" },
  Blender: { icon: SiBlender, color: "#E87D0D" },
};
